### ISSUE TITLE
app become unresponsive after running for a while

### ISSUE THREAD

**Issue by hungrysnake** [iXab3r/MicSwitch#18] opened 2021-01-19 09:33 UTC
hi. thank you so much making this app. i like it alot.

the issue i have with the app is that the app become unresponsive after a period of time (maybe 1-2 hrs). 
the app windows can't even open when double clicking the app icon in the taskbar. I have to close the process from taskmgr to restart it. this issue has happened for multiple times yesterday.

interestingly, the app still respond to the hotkey to toggle the mic mute/unmute.

another suggestions: 
would it be possible to show the live input level in the floating icon? say in green color?

**Comment by iXab3r** [comment] 2021-02-04 09:28
Hi !
That bug with app becoming unresponsive is a priority one, the problem is it's not reproducing on my setup so it's quite hard to catch. I am trying though. 

About another suggestion: sound like a cool idea, will look into implementing it

**Comment by iXab3r** [comment] 2021-03-02 09:55
Should be fixed in 1.0.163, please reopen if it will occur again

**Closed by iXab3r** 2021-03-02 09:55 UTC
