### ISSUE TITLE
after each update microphone settings are reset

### ISSUE THREAD

**Issue by LoneWolfProductions** [iXab3r/MicSwitch#28] opened 2021-03-16 20:03 UTC
after an autoupdate the selected microphone goes from whatever i selected to all microphones.

update.
it also resets to all microphones on a system reset. so i'm thinking its not storing my selection anywhere.

**Comment by iXab3r** [comment] 2021-03-25 12:37
looking into it

**Comment by iXab3r** [comment] 2021-03-25 12:51
I have tried failed to reproduce this behavior using following steps:
1) Select one of microphones instead of "All microphones"
2) Enable option "Run at start"
2) Restart the system

Am I missing something ? The system I've tried it on has 3 microphones and is using Windows 10 20H2

**Comment by iXab3r** [comment] 2021-07-02 12:39
Closing because could not reproduce it. Also some changes were done to ensure something like this won't happen in the future

**Closed by iXab3r** 2021-07-02 12:39 UTC
Labels: bug
