### ISSUE TITLE
MainWindow locks in hidden mode after using "X" button

### ISSUE THREAD

**Issue by Aramil-S** [iXab3r/MicSwitch#10] opened 2020-11-17 09:11 UTC
When I use "X" to send MainWindow to tray, function "Show main windows" ceases to work. Both from context menu and double-click on icon - after clicking nothing happens.
App version: V0.126.0.0
Env: Windows 18363.1082, tried both on user and administrator account

**Comment by iXab3r** [comment] 2020-12-20 13:27
Huge thanks for the report. The fact that this bug reproduces only after pressing X totally avoided my attention. Now the reason is obvious, will fix today.

**Comment by Aramil-S** [comment] 2020-12-20 13:56
No problem. I had similar problem in one of my own apps ;)

**Comment by Aramil-S** [comment] 2020-12-20 13:57
No problem, i had similiar problem in past :)

**Comment by iXab3r** [comment] 2020-12-20 14:13
Fixed in 1.0.133, also added Minimize On Close option which is enabled by default that controls what to do when X is pressed

**Closed** 2020-12-20 14:14 UTC
