### ISSUE TITLE
The microphone and volume levels are reset when the application starts

### ISSUE THREAD

**Issue by im1x** [iXab3r/MicSwitch#98] opened 2022-11-20 17:46 UTC
This problem appeared after the last update.
![demo](https://user-images.githubusercontent.com/1444150/202917549-deffe2f1-b514-407e-88c2-7855ac5f67de.gif)

Version: 1.0.242.0
Windows 10.0.19045.2251
[MicSwitch.release.2022-11-20.1(part).log](https://github.com/iXab3r/MicSwitch/files/10050340/MicSwitch.release.2022-11-20.1.part.log)

**Comment by AngryJKirk** [comment] 2022-11-25 18:02
Same issue here

**Comment by Hansworst85** [comment] 2022-11-28 20:38
Same

**Comment by Playnot** [comment] 2022-12-22 16:34
Same for me, except every device (microphone and playback) goes to 0.

**Comment by Jasongt93** [comment] 2023-01-03 03:58
Same here...  issue on 1.0.242.0

**Comment by iXab3r** [comment] 2023-01-03 14:32
hi guys, got back from vacation, working on it

**Comment by iXab3r** [comment] 2023-01-04 12:50
Done the change, if you can - please help me to test it out, I'll publish new release to github as soon as will be sure that it's stable, probably on a weekend https://eyeauras.blob.core.windows.net/shared/MicSwitchSetup.1.0.248.exe

**Comment by im1x** [comment] 2023-01-04 13:38
> Done the change, if you can - please help me to test it out, I'll publish new release to github as soon as will be sure that it's stable, probably on a weekend https://eyeauras.blob.core.windows.net/shared/MicSwitchSetup.1.0.248.exe

This breaks the volume control. When I change the volume it jumps back to the old level.
![PvnXSl4wT7](https://user-images.githubusercontent.com/1444150/210567159-487138c2-2261-4cf1-aabf-b89f53e7990e.gif)

**Comment by iXab3r** [comment] 2023-01-04 14:16
got it, added new issue - it's not really related to the change as I've not changed how Output volume control is working 
https://github.com/iXab3r/MicSwitch/issues/101

**Comment by im1x** [comment] 2023-01-04 14:30
> got it, thanks created new issue - it's not really related to this bug as I've not touched how Output volume control is working #101

No, this problem is only in 1.0.248, 1.0.240 and 1.0.242 don't have it, I just checked it.

**Comment by im1x** [comment] 2023-01-04 14:53
> Done the change, if you can - please help me to test it out, I'll publish new release to github as soon as will be sure that it's stable, probably on a weekend https://eyeauras.blob.core.windows.net/shared/MicSwitchSetup.1.0.248.exe

Found another problem. When you start the program, it sets the volume and microphone level as it was when you last exited the program.
For instance:
1. The program is running and the volume and microphone are set to 10%;
2. Close the program;
3. Change the volume and microphone level by 30%;
4. Run the program and it will change the levels by 10%;
![9QSEZuPFcs](https://user-images.githubusercontent.com/1444150/210581970-7daa8f1c-1072-4c1a-92bf-6f78993d9521.gif)

**Comment by iXab3r** [comment] 2023-01-04 15:39
Not a problem - this is an expected behaviour, I've described why it was done this way in Discord:

background of this problem is the following: consider you have multiple devices which ALL have their own Mute/Volume states. If you work with a single device getting and setting Volume and Mute state is trivial, but as soon as there are >1 devices involved it gets tricky as it becomes possible that their state will be desynces with each other thus making it not possible to calculate "combined" correct state of either of these values. 

Previous solution was obviously wrong and it simply took minimum volume of all devices and propagated it to all other devices as well. This does not work well in way too many cases.
Current solution will be the following:
1) if you control a single mic it's all good, I simply take Mute/Volume right from device
2) if you switch to All devices from a single mic the I will take Mute/Volume of previously selected device and propagate it to all devices
3) if you start a program with "All devices" being previously selected I will take Mute/Volume of FIRSTdevice in the list which is usually the oldest device installed to the system and it's Mute/Volume state will be propagated to other devices

There is an alternative way for #3 - I can remember last settings that were used and apply them on startup, but I do not think that it is better that my proposal above because it may mess up changes that you've made manually while program was not running 
I think I'll go with alternative - i.e. if Volume Control is enabled MicSwitch will apply latest seen Volume to all devices on app start, in combination with option "Initial Mic State" it seems to be quite logical approach

**Comment by im1x** [comment] 2023-01-04 16:05
> Not a problem - this is an expected behaviour, I've described why it was done this way in Discord:
> 
> background of this problem is the following: consider you have multiple devices which ALL have their own Mute/Volume states. If you work with a single device getting and setting Volume and Mute state is trivial, but as soon as there are >1 devices involved it gets tricky as it becomes possible that their state will be desynced with each other thus making it not possible to calculate "combined" correct state of either of these values.
> 
> Previous solution was obviously wrong and it simply took minimum volume of all devices and propagated it to all other devices as well. This does not work well in way too many cases. Current solution will be the following:
> 
> 1. if you control a single mic it's all good, I simply take Mute/Volume right from device
> 2. if you switch to All devices from a single mic the I will take Mute/Volume of previously selected device and propagate it to all devices
> 3. if you start a program with "All devices" being previously selected I will take Mute/Volume of FIRSTdevice in the list which is usually the oldest device installed to the system and it's Mute/Volume state will be propagated to other devices
> 
> There is an alternative way for #3 - I can remember last settings that were used and apply them on startup, but I do not think that it is better that my proposal above because it may mess up changes that you've made manually while program was not running I think I'll go with alternative - i.e. if Volume Control is enabled MicSwitch will apply latest seen Volume to all devices on app start, in combination with option "Initial Mic State" it seems to be quite logical approach

Thanks for the detailed answer. You're right. It makes sense.

**Comment by iXab3r** [comment] 2023-01-07 13:14
Next iteration of changes (volume control stuttering is still there, do not consider it a blocker and will address) - https://eyeauras.blob.core.windows.net/shared/MicSwitchSetup.1.0.249.exe

**Comment by im1x** [comment] 2023-01-07 21:18
> Next iteration of changes (volume control stuttering is still there, do not consider it a blocker and will address) - https://eyeauras.blob.core.windows.net/shared/MicSwitchSetup.1.0.249.exe

It works well. I didn't find any problems.

**Comment by im1x** [comment] 2023-01-08 14:37
> Next iteration of changes (volume control stuttering is still there, do not consider it a blocker and will address) - https://eyeauras.blob.core.windows.net/shared/MicSwitchSetup.1.0.249.exe

An error has occurred. Error after waking PC from sleep mode. Most likely the error is related to updating the list of media devices (the monitor is connected via HDMI)
[MicSwitch_1.0.249.0_release_202301081434495lbuRWqjQ7EH.zip](https://github.com/iXab3r/MicSwitch/files/10368664/MicSwitch_1.0.249.0_release_202301081434495lbuRWqjQ7EH.zip)

**Comment by iXab3r** [comment] 2023-01-11 10:58
should be fixed in 252, please reopen if it occurs again

**Closed by iXab3r** 2023-01-11 10:58 UTC
