### ISSUE TITLE
Tray icon's tooltip is at top left of main monitor

### ISSUE THREAD

**Issue by Playnot** [iXab3r/MicSwitch#58] opened 2021-08-01 07:26 UTC
The tooltip for the tray icon goes to the top-left of the main monitor, when you mouse over:

![image](https://user-images.githubusercontent.com/60964225/127762931-9a4986b9-5c91-47ec-948f-3baf2ce10f9c.png)

**Comment by iXab3r** [comment] 2021-12-19 21:01
Closing as duplicate of https://github.com/iXab3r/MicSwitch/issues/44

**Closed by iXab3r** 2021-12-19 21:01 UTC
Labels: bug, help wanted, good first issue
